### ISSUE TITLE
TypeError: get_coreclr() takes 0 positional arguments but 1 was given

### ISSUE THREAD

**Issue by Chaleeshadow** [lugia19/ErrorPatcher#2]
` line 108, in pythonnet_init
    rt = get_coreclr(
TypeError: get_coreclr() takes 0 positional arguments but 1 was given`

**Comment by lugia19** [comment]
I can't reproduce this with the packaged release version. Are you running the script directly? What python version are you using?

**Comment by Chaleeshadow** [comment]
python 3.10.6 
sorry I'm still a newbie python 
Yes, I'm running by the script directly.
What should I do with python version? 
then how run script except use running the script directly? 
Thanks!

**Comment by lugia19** [comment]
Well, if your aim is to patch the DEMO (no, it does not work with the full game as that already has an english translation) you just need to follow the instructions in the readme and grab the latest release from the releases page.

I'll be testing to see what the error is either way, but I would recommend using the packaged release if possible.
